# Generated by Django 3.1a1 on 2020-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dff2020', '0002_auto_20200615_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='type',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
