# Generated by Django 3.0 on 2020-07-04 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dff2020', '0004_adding_rating_and_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserRating',
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('shortlist', 'user')},
        ),
    ]
